query FullTextQuery {
  queryComment(filter: { context: { alloftext: "亮" } }) {
    place {
      category
      location {
        latitude
        longitude
      }
      name
    }
    user {
      name
    }
  }
}
